/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gvillena;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.net.IDN;
import java.nio.Buffer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author alond
 */
public class Tarjetas extends javax.swing.JFrame {
    
    
    
     public  double codigo=0 , numero=0 , total=0 , dia=0 , mes=0 ;
     public  String nombre="" , plan ="", modelo="";
    public void me(){
        System.out.println("Se hizo satisfactioramente su compra");
    }
    public Tarjetas() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PanelPrincipal = new javax.swing.JPanel();
        PagoconTarjeta1 = new javax.swing.JLabel();
        Aceptamos1 = new javax.swing.JLabel();
        ImgTarjetas1 = new javax.swing.JLabel();
        NombreTitular1 = new javax.swing.JLabel();
        NumeroTarjeta2 = new javax.swing.JLabel();
        CVV3 = new javax.swing.JLabel();
        FechaCaducidad4 = new javax.swing.JLabel();
        EscribirNombre1 = new javax.swing.JTextField();
        EscribirNumero2 = new javax.swing.JTextField();
        EscribirDia4 = new javax.swing.JTextField();
        EscribirMes5 = new javax.swing.JTextField();
        Mensaje1 = new javax.swing.JLabel();
        OtrosMetoPago1 = new javax.swing.JButton();
        ConfCompra2 = new javax.swing.JButton();
        ImgTarjeta1 = new javax.swing.JLabel();
        ImgTarjeta2 = new javax.swing.JLabel();
        EscribirCodigo3 = new javax.swing.JPasswordField();
        btnSalir = new javax.swing.JButton();
        btnimpri = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtme = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        PanelPrincipal.setBackground(new java.awt.Color(153, 153, 153));
        PanelPrincipal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        PagoconTarjeta1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        PagoconTarjeta1.setText("Pago con Tarjeta");

        Aceptamos1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Aceptamos1.setText("Aceptamos:");

        NombreTitular1.setText("Nombre del Titular");

        NumeroTarjeta2.setText("Numero de la Tarjeta");

        CVV3.setText("CVV (Codigo de seguridad)");

        FechaCaducidad4.setText("Fecha de caducidad de la tarjeta");

        EscribirNombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EscribirNombre1ActionPerformed(evt);
            }
        });

        EscribirNumero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EscribirNumero2ActionPerformed(evt);
            }
        });

        Mensaje1.setBackground(new java.awt.Color(0, 102, 255));
        Mensaje1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Mensaje1.setForeground(new java.awt.Color(0, 51, 204));
        Mensaje1.setText("Confirm your order of 32,66 $ by clicking the button \"Confirm my order\"");

        OtrosMetoPago1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        OtrosMetoPago1.setText("OTROS MÉTODOS DE PAGO");
        OtrosMetoPago1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OtrosMetoPago1ActionPerformed(evt);
            }
        });

        ConfCompra2.setBackground(new java.awt.Color(255, 255, 255));
        ConfCompra2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ConfCompra2.setForeground(new java.awt.Color(0, 102, 255));
        ConfCompra2.setText("CONFIRMAR MI PEDIDO");
        ConfCompra2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfCompra2ActionPerformed(evt);
            }
        });

        ImgTarjeta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BCP (4).png"))); // NOI18N

        ImgTarjeta2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visam (1).png"))); // NOI18N

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnimpri.setBackground(new java.awt.Color(153, 153, 153));
        btnimpri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/impri.png"))); // NOI18N
        btnimpri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimpriActionPerformed(evt);
            }
        });

        jButton1.setText("Atrás");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(OtrosMetoPago1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ConfCompra2)
                .addGap(94, 94, 94))
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                                .addComponent(FechaCaducidad4)
                                .addGap(26, 26, 26)
                                .addComponent(EscribirDia4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(EscribirMes5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createSequentialGroup()
                                        .addComponent(NumeroTarjeta2)
                                        .addGap(18, 18, 18))
                                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Aceptamos1)
                                            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                                                .addGap(16, 16, 16)
                                                .addComponent(CVV3)))
                                        .addGap(14, 14, 14)))
                                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(EscribirCodigo3)
                                    .addComponent(EscribirNumero2, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addContainerGap(13, Short.MAX_VALUE)
                        .addComponent(ImgTarjetas1)
                        .addGap(47, 47, 47)
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                                .addComponent(NombreTitular1)
                                .addGap(21, 21, 21)
                                .addComponent(EscribirNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(ImgTarjeta2)))))
                .addGap(28, 28, 28)
                .addComponent(ImgTarjeta1)
                .addGap(26, 26, 26))
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(Mensaje1))
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(PagoconTarjeta1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnimpri, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PagoconTarjeta1)
                .addGap(14, 14, 14)
                .addComponent(Aceptamos1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addComponent(ImgTarjeta2)
                        .addGap(18, 18, 18)
                        .addComponent(ImgTarjetas1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(NombreTitular1)
                                    .addComponent(EscribirNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)
                                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(NumeroTarjeta2)
                                    .addComponent(EscribirNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(CVV3))
                            .addComponent(EscribirCodigo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EscribirDia4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EscribirMes5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FechaCaducidad4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(Mensaje1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createSequentialGroup()
                                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(OtrosMetoPago1)
                                    .addComponent(ConfCompra2))
                                .addGap(30, 30, 30)
                                .addComponent(btnimpri, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addComponent(ImgTarjeta1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        txtme.setBackground(new java.awt.Color(153, 153, 153));
        txtme.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(txtme, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(47, Short.MAX_VALUE)
                        .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtme, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EscribirNombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EscribirNombre1ActionPerformed
        // TODO add your handling code here:
        
               
    }//GEN-LAST:event_EscribirNombre1ActionPerformed

       
    private void EscribirNumero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EscribirNumero2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EscribirNumero2ActionPerformed

    private void OtrosMetoPago1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OtrosMetoPago1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OtrosMetoPago1ActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
       
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void ConfCompra2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfCompra2ActionPerformed
       txtme.setText("!Se hizo satisfactoriamente su Compra¡");
    }//GEN-LAST:event_ConfCompra2ActionPerformed

    private void btnimpriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimpriActionPerformed

         try {
             mostrarventa();
         } catch (Exception ex) {
             JOptionPane.showMessageDialog(null,"Error "+ ex);
         }
       
      
    }//GEN-LAST:event_btnimpriActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    public void mostrarventa() throws Exception{
    
        nombre=String.format(EscribirNombre1.getText());
        numero = Double.parseDouble(EscribirNumero2.getText());
        codigo = Double.parseDouble(EscribirCodigo3.getText());
        dia =Double.parseDouble(EscribirDia4.getText());
        mes =Double.parseDouble(EscribirMes5.getText());
        
       File fi = new File("D:\\factura.txt");
        FileWriter fw = new FileWriter(fi);
        BufferedWriter bw = new BufferedWriter(fw);
        PrintWriter pw = new PrintWriter(bw);
        pw.write("Nombre:   " + nombre);
        pw.append("\r\nNumero de la Tarjeta:  "+ numero);
        pw.append("\r\nFecha de caducidad de la Tarjeta: " + "\tDia:  "+ dia);
        pw.append("Mes:  " + mes);
        
        bw.close();
        pw.close();
                
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tarjetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tarjetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tarjetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tarjetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tarjetas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Aceptamos1;
    private javax.swing.JLabel CVV3;
    private javax.swing.JButton ConfCompra2;
    private javax.swing.JPasswordField EscribirCodigo3;
    private javax.swing.JTextField EscribirDia4;
    private javax.swing.JTextField EscribirMes5;
    private javax.swing.JTextField EscribirNombre1;
    private javax.swing.JTextField EscribirNumero2;
    private javax.swing.JLabel FechaCaducidad4;
    private javax.swing.JLabel ImgTarjeta1;
    private javax.swing.JLabel ImgTarjeta2;
    private javax.swing.JLabel ImgTarjetas1;
    private javax.swing.JLabel Mensaje1;
    private javax.swing.JLabel NombreTitular1;
    private javax.swing.JLabel NumeroTarjeta2;
    private javax.swing.JButton OtrosMetoPago1;
    private javax.swing.JLabel PagoconTarjeta1;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnimpri;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtme;
    // End of variables declaration//GEN-END:variables
}
